---
version: '3'
services:
  postgres:
    image: postgres:10.5
    environment:
      - TZ=UTC
      - POSTGRES_DB=acca
      - POSTGRES_USER=acca
      - POSTGRES_PASSWORD=acca
    ports:
      - 127.0.0.1:5432:5432
