version: "3"
services:
  PostgreSQL:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=acc
      - DB_PASS=acc
      - DB_NAME=acc
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data: