---
version: '3'
services:
  postgres:
    image: postgres:11
    command: -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.max=10000 -c pg_stat_statements.track=all
    environment:
      - TZ=UTC
      - POSTGRES_DB=acca
      - POSTGRES_USER=acca
      - POSTGRES_PASSWORD=acca
    ports:
      - 5433:5432

